//SJC
#include <SJCLib.h>

//MPEG-1 Video

//MPEG-2 Program Stream
#define MPEG2PS_STARTCODE_PACKHEADER MPEG1SYSTEMS_STARTCODE_PACKHEADER //same as in mpeg1
#define MPEG2PS_STARTCODE_PROGRAMEND 0xB9

/*
//Stream IDs
#define MPEG2PS_STREAMID_VIDEO_FIRST 0xE0
//Other
#define MPEG2PS_PRIVATESTREAM1 0xBD
#define MPEG2PS_PRIVATESTREAM2 0xBF
*/