name: Build Linux x86-64

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    #build and install XP-CMake
    - name: Checkout XP-CMake repo
      uses: actions/checkout@v4
      with:
        repository: aczwink/XP-CMake
        path: xpcmake

    - name: Create build directory for XP-CMake
      run: cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -B ${{github.workspace}}/xpcmake/_build -S ${{github.workspace}}/xpcmake

    - name: Build XP-CMake
      run: cmake --build ${{github.workspace}}/xpcmake/_build --config ${{env.BUILD_TYPE}}

    - name: Install XP-CMake
      run: sudo make install
      working-directory: ${{github.workspace}}/xpcmake/_build

    #install backend/extensions dependencies
    - name: Install dependencies
      run: sudo apt install -y libfuse3-dev

    #build and install Std++
    - name: Checkout Std++ repo
      uses: actions/checkout@v4
      with:
        repository: aczwink/StdPlusPlus
        path: stdpp

    - name: Create build directory for Std++
      run: cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBACKEND_FUSE=ON -B ${{github.workspace}}/stdpp/_build -S ${{github.workspace}}/stdpp

    - name: Build Std++
      run: cmake --build ${{github.workspace}}/stdpp/_build --config ${{env.BUILD_TYPE}}


    # Create release
    - name: Pack release archive
      run: zip --junk-paths bin_linux_x86-64.zip stdpp/_build/libStd++_d.so

    - name: Create or update release
      env:
        GH_TOKEN: ${{ github.token }}
        GHR_TITLE: Latest build
        GHR_NOTES: |
          Latest build of master branch
          Enabled backends/extensions:
          -fuse3
        GHR_FILENAME: bin_linux_x86-64.zip
      run: |
        echo "$GH_TOKEN" > bla.test
        if gh release view latest; then
          gh release edit latest --title "$GHR_TITLE" --notes "$GHR_NOTES"
        else
          gh release create latest --title "$GHR_TITLE" --notes "$GHR_NOTES"
        fi
        gh release upload latest "$GHR_FILENAME" --clobber
